### ISSUE TITLE
 (OpenStack) InfiniBand support

### ISSUE THREAD

**Issue by orviz** [EGI-Federation/cloud-info-provider#125]
# Short Description of the issue

As part of the requirements of DEEP project, we have implemented infiniband support for OpenStack. As described in [1], this implementation relies on the flavor's metadata (extra_specs) in order to extract this information. Both extra_specs' key and value can be provided at runtime via two new command line arguments. 

In the current implementation of cloud-info-provider, infiniband support is available through network_info parameter in the static configuration, but this is VO-wide, not flavor specific. This issue is created to follow the discussion on the best way to integrate DEEP implementation of InfiniBand support.

Might be related with #88 

[1] https://github.com/indigo-dc/cloud-info-provider-deep/blob/DEEP/README-DEEP.md

**Comment by enolfc** [comment]
I think this is nice addition and by reading the description at the DEEP fork, the implementation seems to be doing the right thing. My only doubt is what are the sensible defaults for the new arguments. I'd suggest to send a PR to bring this in.

**Comment by orviz** [comment]
Addressed in #214
