### ISSUE TITLE
Filter out published images

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/cloud-info-provider#17]
Introduce a configuration option specifying which images to export according to
ownership. The administrator would then be able to say "export images
only for the following VOs. Or we can export only images created by vmcatcher.

**Comment by brucellino** [comment]
I realise this issue is hold but I want to help. 

How would this be tested, anyone ?

**Comment by enolfc** [comment]
This is already partially implemented, shamelessly with different options for each provider: 

For the ONE provider, a command line option (--cloudkeeper-images or equivalent --vmcatcher-images) prevents displaying information about those images without AppDB info

For the OS provider, an option in the configuration file (`require_marketplace_id`) does the same.

Would be good to unify implementation
